<a href="https://colab.research.google.com/github/martinasimeone/MLPNS_MSimeone/blob/main/MLPNS_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##EXERCISE:
* create a function that takes a string \\
* checks if the string is a palindrome \\
* returns 1 if true
* return -1 if false
* and also prints “Yes its a palindrome”
* or “this is not a palindrome”
* add a print statement that prints ONLY the unique part (rad in radar)

In [ ]:
def pali(word):
  if type(word) == str:
    word = word.lower()
    rword = word[::-1]
    
    if word == rword:
      print(word,'è una parola palindroma')
    else:
      print(word, 'non è palindroma')
  else:
    print('Devi inserire una stringa')


In [ ]:
pali('ciao')

ciao non è palindroma


In [ ]:
pali('anna')

anna è una parola palindroma


## EXERCISE:
* create a numpy array containing numbers from 1 to 10
* extract only even numbers with boolean operations
* reverse it
* make all those number odd 

In [26]:
import numpy as np

In [34]:
array = np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
even = array[(array % 2) == 0]
even

array([ 2,  4,  6,  8, 10])

In [36]:
reven = even[::-1] 
reven

array([10,  8,  6,  4,  2])

In [38]:
odd = even - 1
odd

array([1, 3, 5, 7, 9])